// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoh-62g3Z8K6l0clTyX3LXXopWBUQKBo8',
    appId: '1:266009804636:web:c98168b208feabd31ecb99',
    messagingSenderId: '266009804636',
    projectId: 'example-project-8093e',
    authDomain: 'example-project-8093e.firebaseapp.com',
    storageBucket: 'example-project-8093e.firebasestorage.app',
    measurementId: 'G-VMBQ2D6FLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTn8uVFu3KdMW1f6WIachuWK8YlzSMFWI',
    appId: '1:266009804636:android:106a880e2d36ee9f1ecb99',
    messagingSenderId: '266009804636',
    projectId: 'example-project-8093e',
    storageBucket: 'example-project-8093e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG_oGQ4m9B50G0ninFr8gc15Lr22bhpKo',
    appId: '1:266009804636:ios:2add0025db6deddd1ecb99',
    messagingSenderId: '266009804636',
    projectId: 'example-project-8093e',
    storageBucket: 'example-project-8093e.firebasestorage.app',
    iosBundleId: 'com.example.baas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG_oGQ4m9B50G0ninFr8gc15Lr22bhpKo',
    appId: '1:266009804636:ios:2add0025db6deddd1ecb99',
    messagingSenderId: '266009804636',
    projectId: 'example-project-8093e',
    storageBucket: 'example-project-8093e.firebasestorage.app',
    iosBundleId: 'com.example.baas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoh-62g3Z8K6l0clTyX3LXXopWBUQKBo8',
    appId: '1:266009804636:web:feff7d5b90875dec1ecb99',
    messagingSenderId: '266009804636',
    projectId: 'example-project-8093e',
    authDomain: 'example-project-8093e.firebaseapp.com',
    storageBucket: 'example-project-8093e.firebasestorage.app',
    measurementId: 'G-F9D15VH4S3',
  );
}
